[ADD] po-msgstr-variables: Check if string translated can be parsed correctly
Identify translation errors when a python string is used to be parsed
    message_id = '%s'
    message_str = '%d'
It will be raise the following error parsing '%d' % ''
    TypeError: %d format: a number is required, not str

Similar case using
    message_id = '{var1}'
    message_str = '{var2}'
It will be raise the following error parsing message_str.format({'var1': ''})
    KeyError: 'var2'

Closes https://github.com/OCA/pylint-odoo/issues/274