[MERGE] From oca/master to vauxoo/master (#50)
* [IMP] translation-required: Just check odoo exceptions

* [FIX] translation-required: Fix AttributeError 'Getattr' object has no attribute 'name'

* [IMP] translation-required: Support .format

* [IMP] translation-required: Support % strings

* [REF] translation-required: 100% coverage

* [IMP] sql-injection: Add compatibility with .format (#44)

* [IMP] deprecated-module: Add exception for the case of valid openerp.osv.expression (#40)

* [IMP] sql-injection: Add compatibility with .format (#44)

* Vx use 2.0 then reverting version change failed