[FIX] prohibited-method-override: Check if caller has a func attribute (#524)
Verify that the caller of a prohibited method to override is a **function** (`super`) using `hasattr(attr.expr, "func")`.

  ```python
  def prohibited_method():
      # ✅ Should not fail (without this fix, pylint-odoo would crash here)
      some_obj.prohibited_method()
  
      # ❌ Should fail
      super().prohibited_method()
  ```

- Without this fix, _pylint-odoo_ crashes with the below exception whenever an object reference (that has no `func` attribute) invokes a method that has the same name as the "_prohibited to override_" method being executed. The check should not fail nor crash, as `super` is not being invoked to apply the override.
  >Traceback (most recent call last):
  >  File "/usr/local/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 87, in walk
  >      callback(astroid)
  >  File "/usr/local/lib/python3.10/site-packages/pylint_odoo/checkers/odoo_addons.py", line 1248, in visit_functiondef
  >      func = attr.expr.func
  >AttributeError: 'Attribute' object has no attribute 'func'
- Modify tests to reflect the extra check.
- Make use of `get_func_name` instead of `func.name`