[FIX] CI: Fix pluggy error on py3.7 and running lint only in one build (#366)
Travis has pre-installed a version of pluggy reproducing the following error when you try to install any pip package:

    Preparing metadata (setup.py) ... error
    error: subprocess-exited-with-error

    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [22 lines of output]
        Traceback (most recent call last):
            File "<string>", line 36, in <module>
            File "<pip-setuptools-caller>", line 14, in <module>
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
            from setuptools.dist import Distribution
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
            from ._importlib import metadata
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 28, in <module>
            disable_importlib_metadata_finder(metadata)
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_importlib.py", line 12, in disable_importlib_metadata_finder
            import importlib_metadata
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 471, in <module>
            __version__ = version(__name__)
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 438, in version
            return distribution(package).version
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 411, in distribution
            return Distribution.from_name(package)
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 179, in from_name
            dists = resolver(name)
            File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 886, in find_distributions
            found = self._search_paths(context.name, context.path)
        AttributeError: 'str' object has no attribute 'name'

It is related to the following thread:
 - https://stackoverflow.com/a/59549323/3753497

It was already fixed running the following command:
 - `pip install -U --force-reinstall pluggy`

Another change in the CI was running lints only for one build instead of all them